### ISSUE TITLE
Add this library to Arduino IDE's builtin repository.

### ISSUE THREAD

**Issue by Avamander** [asheeshr/Microsmooth#3]
It would be really nice if this library could be downloaded and updated from the Arduino IDE.

**Comment by asheeshr** [comment]
This is a really late response, sorry! I didn't get a notification.

I'm not sure what the process is for doing that.

**Comment by tablatronix** [comment]
yes please

**Comment by Avamander** [comment]
@asheeshr One has to create library.propertied file in the root of the repository and then submit a request to the Arduino IDE's Github.
